project:
  type: website

website:
  title: "Connecting OSP"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: news.qmd
        text: News
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    logo: images/logo_osp_isotype.png
    contents:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: news.qmd
        text: News
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



